use_frameworks!

platform :ios, '10.0'

target 'ZJRouter_Example' do
  pod 'ZJRouter', :path => '../'

  target 'ZJRouter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
